### ISSUE TITLE
Compilation error for Go 1.12.5

### ISSUE THREAD

**Issue by akshaydeo** [eycorsican/go-tun2socks-mobile#11]
`make android` works fine on `go 1.11.x` but fails as soon as I switch onto `go 1.12.x`. 

```shell
➜  go-tun2socks-mobile git:(master) make android
mkdir -p /<path>/go_workspace/src/github.com/eycorsican/go-tun2socks-mobile/build
eval "cd /<path>/go_workspace/src/github.com/eycorsican/go-tun2socks-mobile/build && gomobile bind -a -ldflags '-s -w' -target=android -o /<path>/go_workspace/src/github.com/eycorsican/go-tun2socks-mobile/build/tun2socks.aar github.com/eycorsican/go-tun2socks-mobile"
gomobile: /<path>/go_workspace/bin/gobind -lang=go,java -outdir=/var/folders/rm/st94fclx0qvfz2k5pkn1f1h00000gp/T/gomobile-work-398346964 github.com/eycorsican/go-tun2socks-mobile failed: exit status 1
..
..
type-checking package "github.com/eycorsican/go-tun2socks-mobile" failed (/<path>/go_workspace/src/github.com/eycorsican/go-tun2socks-mobile/tun2socks.go:4:2: could not import time (type-checking package "time" failed (/usr/local/go/src/time/sys_unix.go:11:2: could not import syscall (type-checking package "syscall" failed (/usr/local/go/src/syscall/env_unix.go:11:8: could not import sync (type-checking package "sync" failed (/usr/local/go/src/sync/pool.go:9:2: could not import runtime (type-checking package "runtime" failed (/usr/local/go/src/runtime/mem_linux.go:21:6: sysAlloc redeclared in this block)))))))))


make: *** [android] Error 1
```

**Comment by eycorsican** [comment]
travis ci is passing: https://github.com/eycorsican/go-tun2socks-mobile/runs/132832364

**Comment by akshaydeo** [comment]
Could we add following line to travis config and test ?

```
 if [ "$TRAVIS_OS_NAME" = "osx" ]; then make android; ls -l build; fi
```

**Comment by eycorsican** [comment]
Now it builds for both Android and iOS on OSX and the build was also passed.

**Comment by akshaydeo** [comment]
Thank you so much for the help :-).
